CREATE TABLE IF NOT EXISTS beatmapsets (
  id BIGINT NOT NULL PRIMARY KEY,
  artist TEXT NOT NULL DEFAULT "",
  bpm FLOAT NOT NULL DEFAULT 0.0,
  list_cover TEXT NOT NULL DEFAULT "",
  cover TEXT NOT NULL DEFAULT "",
  creator TEXT NOT NULL DEFAULT "",
  play_count BIGINT NOT NULL DEFAULT 0,
  source TEXT NOT NULL DEFAULT "",
  status TEXT NOT NULL DEFAULT "",
  title TEXT NOT NULL DEFAULT "",
  user_id BIGINT NOT NULL DEFAULT 0,
  time_cached TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)