CREATE TABLE IF NOT EXISTS beatmapsets (
  id BIGINT NOT NULL PRIMARY KEY,
  artist VARCHAR(80) NOT NULL DEFAULT '',
  bpm FLOAT NOT NULL DEFAULT 0.0,
  list_cover TEXT NOT NULL DEFAULT '',
  cover TEXT NOT NULL DEFAULT '',
  creator VARCHAR(80) NOT NULL DEFAULT '',
  play_count BIGINT NOT NULL DEFAULT 0,
  source VARCHAR(80) NOT NULL DEFAULT '',
  status VARCHAR(9) NOT NULL DEFAULT '',
  title VARCHAR(80) NOT NULL DEFAULT '',
  user_id BIGINT NOT NULL DEFAULT 0,
  time_cached TIMESTAMPTZ NOT NULL DEFAULT NOW()
)