CREATE TABLE IF NOT EXISTS questions (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  choice1 TEXT NOT NULL,
  choice2 TEXT NOT NULL,
  choice1_answers INTEGER DEFAULT 0 NOT NULL,
  choice2_answers INTEGER DEFAULT 0 NOT NULL
)