CREATE TABLE IF NOT EXISTS beatmaps (
  id BIGINT NOT NULL PRIMARY KEY,
  ar FLOAT NOT NULL DEFAULT 0.0,
  beatmapset_id BIGINT NOT NULL,
  checksum VARCHAR(32),
  max_combo INTEGER NOT NULL DEFAULT 0,
  bpm FLOAT NOT NULL DEFAULT 0.0,
  convert BOOLEAN NOT NULL DEFAULT FALSE,
  count_circles INTEGER NOT NULL DEFAULT 0,
  count_sliders INTEGER NOT NULL DEFAULT 0,
  count_spinners INTEGER NOT NULL DEFAULT 0,
  cs FLOAT NOT NULL DEFAULT 0.0,
  difficulty_rating FLOAT NOT NULL DEFAULT 0.0,
  drain INTEGER NOT NULL DEFAULT 0,
  mode VARCHAR(7) NOT NULL DEFAULT '',
  passcount INTEGER NOT NULL DEFAULT 0,
  playcount INTEGER NOT NULL DEFAULT 0,
  status VARCHAR(9) NOT NULL DEFAULT '',
  total_length INTEGER NOT NULL DEFAULT 0,
  user_id BIGINT NOT NULL DEFAULT 0,
  version VARCHAR(80) NOT NULL DEFAULT '',
  time_cached TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX beatmaps_beatmapmapset_id ON beatmaps (beatmapset_id);